name: Run unit tests on push to main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Yarn
        uses: ./.github/workflows/setup-yarn.yml
        with:
          isMain: true
      - name: Run unit tests
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test.unit
      - name: Run e2e tests
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test.e2e