name: Run unit tests on push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Yarn
        uses: ./.github/actions/setup-yarn
      - name: Run unit tests
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test.unit
      - name: Run e2e tests
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test.e2e