name: Run unit tests on push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Yarn
        uses: frodi-karlsson/carla-planner/.github/actions/setup-yarn@main
      - name: Run unit tests
        run: yarn test.unit
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start