name: Build electron app on push to main

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Yarn
        uses: frodi-karlsson/carla-planner/.github/actions/setup-yarn@main
        with:
          isMain: true
      - name: Build web app
        run: yarn build
      - name: Sync capacitor
        run: yarn sync
      - name: Add electron app
        run: yarn electron:add
      - name: Check for electron folder
        run: |
          if [ ! -d "electron" ]; then
            echo "Electron folder not found"
            exit 1
          fi

