name: Build electron app on push to main

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Yarn
        uses: frodi-karlsson/carla-planner/.github/actions/setup-yarn@main
        with:
          isMain: true
      - name: Build web app
        run: yarn build
      - name: Update capacitor
        run: yarn cap update
      - name: Capacitor copy
        run: yarn cap copy
      - name: Capacitor build electron
        run: cd electron && yarn build
      # Leave this at this for now since we aren't interested in a release yet
      # Later, we will add auto commit and push to a release branch
        

