name: Build electron app on push to main

on: 
  push:
    branches:
      - main

jobs:
  setup-yarn:
    uses: ./.github/workflows/setup-yarn.yml
    with:
      workflows-ref: ./.github/workflows/onpushmain.yml
  build:
    needs: setup-yarn
    runs-on: ubuntu-latest
      - name: Sync capacitor
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: sync

      - name: Build electron app
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: electron

