name: Run unit tests on push to main

on: [push]

jobs:
  setup-yarn:
    uses: ./.github/workflows/setup-yarn.yml
    with:
      workflows-ref: ./.github/workflows/onpush.yml
  test:
    needs: setup-yarn
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test.unit