name: Build electron app on push to main

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Yarn
        uses: frodi-karlsson/carla-planner/.github/actions/setup-yarn@main
        with:
          isMain: true
      - name: Build web app
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build
      - name: Sync capacitor
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: sync
      - name: Build electron app
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: electron

