name: Build electron app on push to main

on: [push]

jobs:
  setup-yarn:
    uses: ./.github/workflows/setup-yarn.yml
  build:
    runs-on: ubuntu-latest
      - name: Sync capacitor
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: sync

      - name: Build electron app
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: electron

