name: Build electron app on push to main

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Yarn
        uses: frodi-karlsson/carla-planner/.github/workflows/setup-yarn.yml@main
        with:
          isMain: true
      - name: Sync capacitor
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: sync

      - name: Build electron app
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: electron

