name: Setup Yarn

on: [workflow_call]

jobs:
  setup-yarn:
    runs-on: ubuntu-latest
    inputs:
      workflows-ref:
          description: "ref of the centralized workflows repo that was specified in 'jobs.<name>.uses'"
          required: true
          type: string
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: |
          corepack enable
      
      - name: Set yarn node resolution to node-modules
        run: |
          yarn config set nodeLinker node-modules

      - name: Set yarn npm registry
        run: |
          yarn config set npmRegistryServer "https://registry.npmjs.org"

      - name: Install dependencies
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
