name: Setup Yarn
description: Setup Yarn for use in other jobs
inputs:
  isMain:
    description: 'Is this the main branch?'
    required: true
    default: false
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - run: |
        corepack enable
    
    - name: Set yarn node resolution to node-modules
      run: |
        yarn config set nodeLinker node-modules

    - name: Set yarn npm registry
      run: |
        yarn config set npmRegistryServer "https://registry.npmjs.org"

    - name: Install dependencies
      uses: borales/actions-yarn@v4.2.0
      with:
        cmd: install
